### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by sensible-heart** [CMPUT401Team/CMPUT401Project#2]
Build off existing account creation tools to allow for different types of user account creation.
- [ ] Grab a list of sign in information from Julia. Put it Here.

Linked Issues:
- [ ] #1 Create Novice User
- [ ] #3 Create an Expert User
- [ ] #4 Create an Administrator User
